import type { Directions } from '@nuxtjs/i18n'
import type { Locale } from 'vue-i18n'

//type LocaleKey = (typeof availableLocales)[number]

/**
 * Translation status data generated by Lunaria build
 */
export interface I18nStatus {
  /** ISO timestamp when this status was generated */
  generatedAt: string
  /** The source locale (English) */
  sourceLocale: {
    lang: string
    label: string
    totalKeys: number
  }
  /** Status for each target locale */
  locales: I18nLocaleStatus[]
}

export interface I18nLocaleStatus {
  /** Locale code (e.g., 'fr', 'zh-CN') */
  lang: Locale
  /** Display name (e.g., 'Français') */
  label: string
  /** locale direction - rtl | ltr */
  dir: Directions
  /** Total number of translation keys */
  totalKeys: number
  /** Number of completed translations */
  completedKeys: number
  /** List of missing key paths (dot notation) */
  missingKeys: string[]
  /** Completion percentage (0-100) */
  percentComplete: number
  /** GitHub URL to edit this locale file */
  githubEditUrl: string
  /** GitHub URL to view history of this locale file */
  githubHistoryUrl: string
}

export interface FileStatus extends Omit<I18nLocaleStatus, 'lang'> {
  file: string
  lang: string
}

export interface FileEntryStatus extends FileStatus {
  done: number
  missing: number
}
